name: Dependency Review

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review
    runs-on: ubuntu-latest
    if: ${{ ! github.event.repository.private }}
    steps:
      - name: Generate review
        uses: actions/dependency-review-action@v4
        with:
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 600 # 10 minutes
          comment-summary-in-pr: true
